version: '2'
services:
  benchmark:
    build: ./subscribers
    links:
    - slanger
    command: bin/thor -A 10 -W 10 -M 1 -K 123 ws://slanger:8080
    depends_on:
      - slanger
  slanger:
    build: ./slanger
    ports:
    - "4567:4567"
    - "8080:8080"
    links:
    - redis
    command: slanger --app_key 123 --secret 123 --redis_address redis://redis:6379/0
    depends_on:
      - redis
  redis:
    build:
      context: ./redis
