version: '2'
services:
  benchmark:
    build: ./slanger-client
    links:
    - slanger
    command: ruby benchmark.rb -a http://slanger:4567 -w ws://slanger:8080 -i abc -k 123 -s 123 -c 1000 -n 1000 --size 20
    depends_on:
      - slanger
  slanger:
    build: ./slanger
    ports:
    - "4567:4567"
    - "8080:8080"
#    volumes:
#    - .:/code
#    - logvolume01:/var/log
    links:
    - redis
    command: slanger --app_key 123 --secret 123 --redis_address redis://redis:6379/0
    depends_on:
      - redis
  redis:
    build:
      context: ./redis
#volumes:
#  logvolume01: {}
